APP_TOKEN = "INSERT TOKEN HERE"

MYSQL_HOST = "HOST_NAME_HERE"
MYSQL_USER = "ROOT_NAME_HERE"
MYSQL_PASSWORD = "your_password_here"
MYSQL_DATABASE = "metrobike_dw"


REDSHIFT_HOST = "HOST_HERE"
REDSHIFT_PORT = 1234
REDSHIFT_DB = "dev"
REDSHIFT_USER = "USER ID"
REDSHIFT_PASSWORD = "PASSWORD_HERE"
